{{=<( )>=}}
\section{\en{Experience}\cn{项目经验}}
<(#experience)>
<(^subsection)>
<(#start)>
\cventry{%
<(#end)>
\daterange{<(start)>}{<(end)>}%
<(/end)>
<(^end)>
\datetilnow{<(start)>}%
<(/end)>
}
<(/start)>
{%title
<(#title)>
\en{<({en})>}%
\cn{<({cn})><(#note_cn)>{\tiny{(<({en})>)}}<(/note_cn)>}%
<(/title)>
}
{%employer
<(#employer)>
\en{<({en})>}%
\cn{<({cn})>}%
<(/employer)>
}
{%city
<(#city)>
\en{<({en})>}%
\cn{<({cn})>}%
<(/city)>
}
{%nation
}
{%description
<(#description)>
\en{<({en})>}%
\cn{<({cn})>}%
<(/description)>
}
<(/subsection)>
<(#subsection)>
<(^breakable)>
\begin{mynopagebreak}
<(/breakable)>
\subsection{\en{<(en)>}\cn{<(cn)>}}
<(#experience)>
<(#start)>
\cventry{%
<(#end)>
\daterange{<(start)>}{<(end)>}%
<(/end)>
<(^end)>
\datetilnow{<(start)>}%
<(/end)>
}
<(/start)>
{%title
<(#title)>
\en{<({en})>}%
\cn{<({cn})><(#note_cn)>{\tiny{(<({en})>)}}<(/note_cn)>}%
<(/title)>
}
{%employer
<(#employer)>
\en{<({en})>}%
\cn{<({cn})>}%
<(/employer)>
<(#github)>
\githubsocialsymbol\href{https://github.com/<(github)>}{<(github)>}%
<(/github)>
}
{%city
<(#city)>
\en{<({en})>}%
\cn{<({cn})>}%
<(/city)>
}
{%nation
}
{%description
<(#description)>
\en{<({en})>}%
\cn{<({cn})>}%
\newline{}
<(/description)>
<(#skills)>
	%\en{Skills:}%
	%\cn{技能：}%
	\begin{inparaitem}
<(#items)>
		\item <({.})>
<(/items)>
	\end{inparaitem}
<(/skills)>
}
<(/experience)>
<(^breakable)>
\end{mynopagebreak}
<(/breakable)>
<(/subsection)>
<(/experience)>
