name: 'Patch PDF'
description: 'patch the generated pdf'
inputs:
  pdf: 
    description: 'the pdf filepath'
    required: true
    default: 'main.pdf'
  outputs:
    pdf:
      description: 'the patched pdf filepath'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pdf }}
